Worked on NATS container and started DefaultNotificationSender class

diff --git a/nats-init b/nats-init
--- a/nats-init
+++ b/nats-init
@@ -9,16 +9,31 @@
 command -v docker > /dev/null 2>&1 || (echo >&2 "Docker not installed. Exiting."; exit 1; )
 docker version > /dev/null 2>&1 || (echo >&2 "Docker isn't running. Exiting."; exit 1; )
 
-# Options
-if [ $# -ne 1 ]; then
-	echo "No options supplied, or too many. Options are start or stop."
-	exit 1
-elif [ $1 = "start" ]; then
+function start {
 	echo "Starting nats streaming server"
-	docker start nats-streaming-dev 2>/dev/null || docker run -p 4222:4222 -p 8222:8222 --name nats-streaming-dev -d nats-streaming
-elif [ $1 = "stop" ]; then
+	docker start nats-streaming-dev 2>/dev/null || docker run -p 4222:4222 -p 8222:8222 -v nats-store --name nats-streaming-dev -d nats-streaming
+}
+function stop {
 	echo "Stopping nats streaming server"
 	docker stop nats-streaming-dev
+}
+
+# Options
+if [ $# -ne 1 ]; then
+	echo "No options supplied, or too many. Options are start, stop, restart, or reload."
+	exit 1
+elif [ $1 = "start" ]; then
+	start
+elif [ $1 = "stop" ]; then
+	stop
+elif [ $1 = "restart" ]; then
+	stop
+	start
+elif [ $1 = "reload" ]; then
+	echo "Running new build of nats-streaming"
+	stop
+	docker rm nats-streaming-dev
+	start
 else
-	echo "Invalid option. Options are start or stop."
+	echo "Invalid option. Options are start, stop, load, or reload."
 fi
